### ISSUE TITLE
'priorsense' no longer works for the 'brms' object

### ISSUE THREAD

**Issue by Sandhu-SS** [n-kall/priorsense#55]

**Comment by n-kall** [comment]
Thanks for reporting this! I think it should be fixed if you install the latest brms version from github (which now contains the `log_prior_draws.brmsfit` function).

**Comment by Sandhu-SS** [comment]
Hi, 

Thank you for looking into it. 

I have installed the latest ```priorsense``` (version ‘1.0.1’) but it still does not work. 

I think we need ```log_lik``` as well which is not available by default.  Please see below.

```
powerscale_sensitivity(fit1$fit)
Error in check_pars(allpars, pars) : no parameter log_lik
```

PS: Also, it would be great if 'stanfit' is extracted internally i.e., calling ```powerscale_sensitivity(fit1)``` instead of ```powerscale_sensitivity(fit1$fit)```.

**Comment by paul-buerkner** [comment]
You need to run powerscale_sensitivity(fit1)

**Comment by n-kall** [comment]
> I have installed the latest priorsense (version ‘1.0.1’) but it still does not work.

Can you try with the github version of `brms`? The functions needed were moved there

**Comment by Sandhu-SS** [comment]
Thank you @n-kall and @paul-buerkner 

Works perfectly fine after installing the latest `version of the ``brms```

**Comment by n-kall** [comment]
A new brms was uploaded to CRAN (2.22) so this is no longer an issue
